### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by slavakurilyak** [MichaelMMeskhi/MLRP#6]
Running `$ python flask_app.py` on Python 2.7, then clicking `submit` button produces the following error:

```
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1736]
PdfReadWarning: Superfluous whitespace found in object header 1 0 [pdf.py:1666]
PdfReadWarning: Superfluous whitespace found in object header 2 0 [pdf.py:1666]
PdfReadWarning: Superfluous whitespace found in object header 3 0 [pdf.py:1666]
PdfReadWarning: Superfluous whitespace found in object header 36 0 [pdf.py:1666]
PdfReadWarning: Superfluous whitespace found in object header 44 0 [pdf.py:1666]
 * Serving Flask app "flask_app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/May/2018 11:56:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2018 11:56:11] "GET /css/normalize.css HTTP/1.1" 404 -
127.0.0.1 - - [20/May/2018 11:56:11] "GET /css/skeleton.css HTTP/1.1" 404 -
/Users/skurilyak/dev/testing/MichaelMMeskhi/MLRP/testresumes/
[2018-05-20 11:56:16,641] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/Users/skurilyak/Envs/MLRP-98OiywCA/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skurilyak/Envs/MLRP-98OiywCA/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skurilyak/Envs/MLRP-98OiywCA/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skurilyak/Envs/MLRP-98OiywCA/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skurilyak/Envs/MLRP-98OiywCA/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_app.py", line 92, in upload
    if result[0]==1:
UnboundLocalError: local variable 'result' referenced before assignment
127.0.0.1 - - [20/May/2018 11:56:16] "POST /upload HTTP/1.1" 500 -
```

<img width="512" alt="screen shot 2018-05-20 at 11 57 00 am" src="https://user-images.githubusercontent.com/6625584/40282482-ee4aab6a-5c24-11e8-9471-ce5dabe08f61.png">

**Comment by MichaelMMeskhi** [comment]
The server that this used to run on was shutdown. You would have to host it or change to another server.
